#############################################
# I like to leave lots of comments in these #
# yaml files because nobody does but it's a #
# nice feature. :)                          #
#############################################

# This will be BEss because BEss-Bukkit is for Maven..
name: 'BEss'

# The main class, if I obf this remember to have this change.
main: 'co.ryred.bess.bukkit.BEssPlugin'

# MEEEEEE. :D Would be nice if there was a contributers section..
author: 'Cory Redmond'

# Description for this plugin.
description: 'This is the Bukkit side for BEss that allows for communication.'

# Maybe I'll steal the plugin from md-5 where we can have both versions..
version: '${pom.version}-b#${env.BUILD_NUMBER};${env.MASTER_BUILD}'

# We need protocol lib.
depend:
  - 'ProtocolLib'